export { default as BusinessServiceSchema } from "./businessService.model";
export { default as ColorSchema } from "./color.model";
export { default as ConfigSchema } from "./config.model";
export { default as ContactUsSchema } from "./contactUs.model";
export { default as CouponSchema } from "./coupon.model";
export { default as DevicesSchema } from "./device.model";
export { default as EvaluationSchema } from "./evaluation.model";
export { default as EvaluationPriceSchema } from "./evaluationPrice.model";
export { default as JoinOurTeamSchema } from "./joinOurTeam.model";
export { default as MakeSchema } from "./make.model";
export { default as MemorySchema } from "./memory.model";
export { default as NotificationSchema } from "./notification.model";
export { default as ReviewSchema } from "./review.model";
export { default as SalePriceModel } from "./salePrice.model";
export { ServicePropertySchema } from "./serviceProperty.model";
export { ServicePropertyValueSchema } from "./servicePropertyValue.model";
export { ServicePriceModel } from "./servicePrice.model";
export { default as SupportSchema } from "./support.model";
export { default as TimingSchema } from "./timing.model";
